/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-20 05:57:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_spring_project3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/_java_config_security/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685681159057L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("  <main>\n");
      out.write("    <div class=\"py-5 text-center\">\n");
      out.write("      <img class=\"d-block mx-auto mb-4\" src=\"/resources/image/icons-hero.png\" alt=\"\" width=\"72\" height=\"57\">\n");
      out.write("      <h2>Product Detail</h2>\n");
      out.write("      <p class=\"lead\">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"row g-5\">\n");
      out.write("      <div class=\"col-md-5 col-lg-4 order-md-last\">\n");
      out.write("        <h4 class=\"d-flex justify-content-between align-items-center mb-3\">\n");
      out.write("          <span class=\"text-primary\">Your cart</span>\n");
      out.write("          <span class=\"badge bg-primary rounded-pill\">3</span>\n");
      out.write("        </h4>\n");
      out.write("        <ul class=\"list-group mb-3\">\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between lh-sm\">\n");
      out.write("            <div>\n");
      out.write("              <h6 class=\"my-0\">Product name</h6>\n");
      out.write("              <small class=\"text-muted\">Brief description</small>\n");
      out.write("            </div>\n");
      out.write("            <span class=\"text-muted\">$12</span>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between lh-sm\">\n");
      out.write("            <div>\n");
      out.write("              <h6 class=\"my-0\">Second product</h6>\n");
      out.write("              <small class=\"text-muted\">Brief description</small>\n");
      out.write("            </div>\n");
      out.write("            <span class=\"text-muted\">$8</span>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between lh-sm\">\n");
      out.write("            <div>\n");
      out.write("              <h6 class=\"my-0\">Third item</h6>\n");
      out.write("              <small class=\"text-muted\">Brief description</small>\n");
      out.write("            </div>\n");
      out.write("            <span class=\"text-muted\">$5</span>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between bg-light\">\n");
      out.write("            <div class=\"text-success\">\n");
      out.write("              <h6 class=\"my-0\">Promo code</h6>\n");
      out.write("              <small>EXAMPLECODE</small>\n");
      out.write("            </div>\n");
      out.write("            <span class=\"text-success\">−$5</span>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"list-group-item d-flex justify-content-between\">\n");
      out.write("            <span>Total (USD)</span>\n");
      out.write("            <strong>$20</strong>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <form class=\"card p-2\">\n");
      out.write("          <div class=\"input-group\">\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Promo code\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-secondary\">Redeem</button>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("<!-- 상품상세정보란 시작 -->\n");
      out.write("      <div class=\"col-md-7 col-lg-8\">\n");
      out.write("        <h4 class=\"mb-3\">Product information</h4>\n");
      out.write("        <form action=\"/product/modify\" method=\"post\">\n");
      out.write("        <input type=\"hidden\" name=\"pno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.pno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("          <div class=\"row g-3\">\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"email\" class=\"form-label\">Writer</label>\n");
      out.write("              <div class=\"input-group has-validation\">\n");
      out.write("                <span class=\"input-group-text\">@</span>\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"writer\"\n");
      out.write("                id=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>              \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"regAt\" class=\"form-label\">Reg At</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.regAt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>              \n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"modAt\" class=\"form-label\">Mod At</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.modAt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>              \n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"readCount\" class=\"form-label\">Read Count</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.readCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>              \n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"cmtQty\" class=\"form-label\">Comment Qty.</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.cmtQty }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>              \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"pname\" class=\"form-label\">Product Name</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"pname\"\n");
      out.write("               id=\"pname\" placeholder=\"Product Name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.pname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readOnly>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <label for=\"desc\" class=\"form-label\">Description</label>\n");
      out.write("              <textarea class=\"form-control\" name=\"description\" readOnly\n");
      out.write("               id=\"desc\" placeholder=\"Description\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-5\">\n");
      out.write("              <label for=\"madeBy\" class=\"form-label\">Made By</label>\n");
      out.write("              ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              <select class=\"form-select\" name=\"madeBy\" id=\"madeBy\"\n");
      out.write("               required disabled>\n");
      out.write("                <option value=\"\">Choose...</option>\n");
      out.write("                <option value=\"us\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${madeby eq 'us' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">United States</option>\n");
      out.write("                <option value=\"ko\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${madeby eq 'ko' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Korea</option>\n");
      out.write("                <option value=\"cn\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${madeby eq 'cn' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">China</option>\n");
      out.write("                <option value=\"eu\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${madeby eq 'eu' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">European Union</option>\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("              <label for=\"cate\" class=\"form-label\">Category</label>\n");
      out.write("              ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              <select class=\"form-select\" name=\"category\" id=\"category\"\n");
      out.write("               required disabled>\n");
      out.write("                <option value=\"\">Choose...</option>\n");
      out.write("                <option value=\"Clothes\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate eq 'Clothes' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Clothes</option>\n");
      out.write("                <option value=\"Electronic\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate eq 'Electronic' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Electronic</option>\n");
      out.write("                <option value=\"Food\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate eq 'Food' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Food</option>\n");
      out.write("                <option value=\"Health\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate eq 'Health' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Health</option>\n");
      out.write("                <option value=\"Media\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cate eq 'Media' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Media</option>\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("              <label for=\"price\" class=\"form-label\">Price</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"price\"\n");
      out.write("               id=\"price\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required readOnly>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("    	   	<button type=\"button\" id=\"modBtn\" class=\"btn btn-outline-warning\">MOD</button>\n");
      out.write("    		<button type=\"button\" id=\"delBtn\" class=\"btn btn-outline-danger\">DEL</button>\n");
      out.write("        </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("<form action=\"/product/remove\" method=\"post\" id=\"delForm\">\n");
      out.write("	<input type=\"hidden\" name=\"pno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pvo.pno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("</form>\n");
      out.write("<!-- 댓글영역 시작 -->\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"input-group my-3\">\n");
      out.write("	<span class=\"input-group-text\" id=\"cmtWriter\">Anonymous</span>\n");
      out.write("	<input type=\"text\" class=\"form-control\" id=\"cmtText\" value=\"Test Add Comment \">\n");
      out.write("	<button class=\"btn btn-success\" id=\"cmtPostBtn\" type=\"button\">Post</button>\n");
      out.write("</div>\n");
      out.write("<ul class=\"list-group list-group-flush\" id=\"cmtListArea\">\n");
      out.write("  <li class=\"list-group-item d-flex justify-content-between align-items-start\">\n");
      out.write("    <div class=\"ms-2 me-auto\">\n");
      out.write("      <div class=\"fw-bold\">Writer</div>\n");
      out.write("      Content for Comment\n");
      out.write("    </div>\n");
      out.write("    <span class=\"badge bg-dark rounded-pill\">modAt</span>\n");
      out.write("  </li>\n");
      out.write("</ul>\n");
      out.write("<div class=\"row\">\n");
      out.write("	<div class=\"col\"></div>\n");
      out.write("	<div class=\"col d-grid\">\n");
      out.write("		<button type=\"button\" id=\"moreBtn\" data-page=\"1\"\n");
      out.write("		 class=\"btn btn-outline-secondary btn-block\" style=\"visibility: hidden\">\n");
      out.write("		MORE +</button>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"col\"></div>\n");
      out.write("</div>\n");
      out.write("<!-- The Modal -->\n");
      out.write("<div class=\"modal\" id=\"myModal\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("      <!-- Modal Header -->\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h4 class=\"modal-title\">Anonymous</h4>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Modal body -->\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <div class=\"input-group my-3\">\n");
      out.write("			<input type=\"text\" class=\"form-control\" id=\"cmtTextMod\">\n");
      out.write("			<button class=\"btn btn-success\" id=\"cmtModBtn\" type=\"button\">Post</button>\n");
      out.write("		</div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Modal footer -->\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("const pnoVal = document.querySelector(\"input[name=pno]\").value;\n");
      out.write("\n");
      out.write("document.addEventListener(\"click\", (e) => {\n");
      out.write("	 if(e.target.id == 'delBtn') {\n");
      out.write("	        e.preventDefault();\n");
      out.write("	        document.querySelector(\"#delForm\").submit();\n");
      out.write("	 }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script src=\"/resources/js/product.comment.js\"></script>\n");
      out.write("<script>\n");
      out.write("let isMod = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("if (parseInt(isMod)) {\n");
      out.write("	alert('상품 수정 성공~');\n");
      out.write("}\n");
      out.write("getCommentList(pnoVal);\n");
      out.write("</script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/product/detail.jsp(111,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("madeby");
      // /WEB-INF/views/product/detail.jsp(111,14) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/detail.jsp(111,14) '${pvo.madeBy }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pvo.madeBy }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/product/detail.jsp(124,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("cate");
      // /WEB-INF/views/product/detail.jsp(124,14) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/product/detail.jsp(124,14) '${pvo.category }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pvo.category }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/product/detail.jsp(218,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isMod}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
